# Generated by Django 2.2 on 2020-09-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IATA_code', models.CharField(max_length=3, unique=True)),
                ('city_name', models.CharField(max_length=128)),
                ('railway_station_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('AP', 'Airplane'), ('TR', 'Train'), ('BS', 'Bus'), ('TX', 'Taxi')], default='AP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='GroundTransportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_tickets', models.PositiveIntegerField(blank=True, null=True)),
                ('seat_type', models.CharField(blank=True, max_length=20, null=True)),
                ('train_number', models.CharField(blank=True, max_length=20, null=True)),
                ('depart_date', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=15)),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_from', to='flights.Airport')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_to', to='flights.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_date', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=15)),
                ('number_of_changes', models.PositiveIntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Carrier')),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='flights.Airport')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='flights.Airport')),
            ],
        ),
    ]
