# Generated by Django 2.2 on 2020-09-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airport',
            table='flights_airport',
        ),
    ]
