# Generated by Django 2.2 on 2020-09-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='carrier',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
