# Generated by Django 2.2 on 2020-09-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20200907_1942'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airport',
            table='flights_airports',
        ),
    ]
