# Generated by Django 2.2 on 2020-09-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20200907_1943'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airport',
            table=None,
        ),
    ]
